apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpulse
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpulse
  template:
    metadata:
      labels:
        app: kpulse
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kpulse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kpulse"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
